# Generated by Django 3.1.2 on 2020-10-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscellany', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Marca')),
                ('features', models.CharField(max_length=255, verbose_name='Caracteristicas')),
                ('country', models.CharField(max_length=300, verbose_name='Pais')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
    ]
