# Generated by Django 3.1.2 on 2020-10-23 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miscellany', '0002_auto_20201023_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='country',
            field=models.CharField(max_length=300, verbose_name='Pais de la marca'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('expire', models.DateField(verbose_name='Fecha de expiración')),
                ('modelyear', models.DateField(verbose_name='Año de modelo')),
                ('listprice', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio de lista')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Cantidad')),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miscellany.brand', verbose_name='Marca')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miscellany.category', verbose_name='Categoria')),
            ],
        ),
    ]
