# Generated by Django 3.1.2 on 2020-11-11 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miscellany', '0003_auto_20201023_0253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
