# Generated by Django 3.1.2 on 2020-11-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscellany', '0005_dealer'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre cliente')),
                ('last_name', models.CharField(max_length=200, verbose_name='Apellido(s)')),
                ('bithday', models.DateField(verbose_name='Fecha de nacimiento')),
                ('gender', models.CharField(max_length=50, verbose_name='Genero')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Montos',
            },
        ),
    ]
