# Generated by Django 3.1.2 on 2020-11-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscellany', '0006_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha de compra')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Monto a pagar')),
            ],
            options={
                'verbose_name': 'Monto',
            },
        ),
    ]
